load("//:txt.bzl", "txt_library")

txt_library(
    name = "lib13",
    srcs = ["foo.txt"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib14",
        "//lib15",
        "//lib16",
    ],
)
