load("//:txt.bzl", "txt_library")

txt_library(
    name = "lib14",
    srcs = ["foo.txt"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib15",
        "//lib16",
        "//lib17",
        "//lib18",
    ],
)
