name: Pull Request
on: pull_request

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b
        with:
          version: 8.6.7

      - name: Run Tests
        run: |
          pnpm install
          pnpm test
